import React from 'react';
import { FileText, Download, Printer } from 'lucide-react';

const EnvironmentalReports = () => {

  const handleExport = (rep) => {
    // For the hackathon, we simulate downloading a file
    const content = `Report: ${rep.title}\nDate: ${rep.date}\nDescription: ${rep.desc}\n\nGenerated by EcoSphere ESG Platform`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    
    const a = document.createElement('a');
    a.href = url;
    a.download = `${rep.title.replace(/\s+/g, '_')}_Report.${rep.type.toLowerCase()}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-slate-800 flex items-center gap-2">
          <FileText className="text-emerald-600" /> Environmental Reports
        </h1>
        <p className="text-slate-500 mt-1">Generate and export automated compliance and performance reports.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {[
          { title: 'Annual GHG Emissions Report', desc: 'Comprehensive breakdown of Scope 1, 2, and 3 emissions for the fiscal year.', type: 'TXT', date: 'Dec 31, 2025' },
          { title: 'Department Carbon Footprint', desc: 'Comparative analysis of carbon emissions across all departments.', type: 'CSV', date: 'Last Month' },
          { title: 'Sustainability Goals Progress', desc: 'Status update on all active environmental targets and net-zero milestones.', type: 'TXT', date: 'Current' },
          { title: 'Supply Chain ESG Audit', desc: 'Supplier emission factors and product life cycle carbon analysis.', type: 'CSV', date: 'Q3 2025' }
        ].map((rep, i) => (
          <div key={i} className="bg-white p-6 rounded-2xl border border-slate-100 shadow-sm flex flex-col justify-between group">
            <div>
              <div className="flex justify-between items-start mb-3">
                <span className="px-2.5 py-1 bg-slate-100 text-slate-600 font-semibold text-xs rounded-lg">{rep.type}</span>
                <span className="text-xs text-slate-400 font-medium">{rep.date}</span>
              </div>
              <h3 className="font-bold text-slate-800 text-lg mb-2">{rep.title}</h3>
              <p className="text-sm text-slate-500 line-clamp-2">{rep.desc}</p>
            </div>
            
            <div className="mt-6 pt-4 border-t border-slate-100 flex gap-3">
              <button onClick={() => handleExport(rep)} className="flex-1 flex items-center justify-center gap-2 py-2 bg-emerald-50 text-emerald-700 font-semibold rounded-xl text-sm hover:bg-emerald-100 transition-colors">
                <Download size={16} /> Export
              </button>
              <button onClick={handlePrint} className="px-4 py-2 bg-slate-50 text-slate-600 rounded-xl hover:bg-slate-100 transition-colors">
                <Printer size={16} />
              </button>
            </div>
          </div>
        ))}
      </div>
      
      <div className="bg-slate-800 rounded-2xl p-6 text-white shadow-sm flex flex-col md:flex-row items-center justify-between gap-6">
        <div>
          <h3 className="text-xl font-bold mb-1">Custom Reporting Tool</h3>
          <p className="text-slate-400 text-sm">Need specific data? Build a custom report with our advanced query builder.</p>
        </div>
        <button onClick={() => alert('Custom Report Builder will be available in v2.0!')} className="px-6 py-2.5 bg-emerald-500 hover:bg-emerald-400 text-slate-900 font-bold rounded-xl text-sm transition-colors shrink-0 whitespace-nowrap">
          Launch Builder
        </button>
      </div>
    </div>
  );
};

export default EnvironmentalReports;
